"""create election accreditation table

Revision ID: 804aca9cf57c
Revises: 93e273db12a6
Create Date: 2026-05-22 17:16:44.938217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804aca9cf57c'
down_revision: Union[str, Sequence[str], None] = '93e273db12a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accreditations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registry_row_id', sa.Integer(), nullable=False),
    sa.Column('accredited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_row_id'], ['election_voter_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'user_id', name='uq_election_user_accreditation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accreditations')
    # ### end Alembic commands ###
